[book]
name = "Apollo Documentation"
authors = ["Apollo Team"]
description = "Documentation for the Apollo language implementation toolkit"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/apollo"
edit-url-template = "https://github.com/yourusername/apollo/edit/main/docs-mdbook/{path}"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.html.playground]
editable = true
copyable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.mermaid]
command = "mdbook-mermaid" 