baseURL = 'https://yourusername.github.io/apollo/'
languageCode = 'en-us'
title = 'Apollo - Racket to Luau Compiler'
theme = 'book'

# Book theme settings
[params]
  # Show or hide table of contents by default
  BookToC = true
  
  # Set source repository location
  BookRepo = 'https://github.com/yourusername/apollo'
  
  # Enable "Edit this page" links
  BookEditPath = 'edit/main/docs-hugo/content'
  
  # Hide "Edit this page" links on the following paths
  BookEditPathExclude = ['']
  
  # Set menu ordering
  BookMenuBundle = '/menu'
  
  # Set search functionality
  BookSearch = true
  
  # Set Git repository information
  BookCommitPath = 'commit'

[menu]
  [[menu.before]]
    name = "GitHub"
    url = "https://github.com/dunnoconz/apollo"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown 