baseURL = "https://dunnoconz.github.io/apollo/" # CHANGE THIS
languageCode = "en-us"
title = "Apollo Compiler Documentation"
theme = "blowfish" # Add a theme later, e.g., "ananke" or "book"

[params]
  description = "Documentation for the Apollo Racket-to-Luau Compiler"

# Needed for Github pages deployment if using root repository
# publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "guide"
    name = "Guide"
    url = "/guide/"
    weight = 10
  [[menu.main]]
    identifier = "api"
    name = "API Reference"
    url = "/api/" # Link to where Racket docs will be hosted
    weight = 20 
