name: Build Apollo Binary

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Apollo Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_name: apollo-linux
          - os: macos-latest
            output_name: apollo-macos
          - os: windows-latest
            output_name: apollo-windows.exe

    steps:
    - uses: actions/checkout@v4

    - name: Set up Racket
      uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.9'

    - name: Install Apollo package
      run: |
        raco pkg install --auto --scope user apollo

    - name: Create output directory
      run: mkdir -p out

    - name: Build binary
      run: |
        raco exe --gui -o "out/${{ matrix.output_name }}" src/apollo/main.rkt
        raco distribute "out/dist-${{ matrix.output_name }}" "out/${{ matrix.output_name }}"

    - name: Upload binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apollo-binary-${{ matrix.os }}
        path: out/dist-${{ matrix.output_name }}

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          out/dist-${{ matrix.output_name }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 