name: Racket CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Racket
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.16'
    
    # Removed explicit installation of rackunit/scribble-lib as they should be pre-installed
    # - name: Install external dependencies
    #   run: raco pkg install --batch rackunit scribble-lib
    
    - name: Link local package
      run: raco pkg install --batch
    
    - name: Setup apollo package (compile)
      run: raco setup apollo
    
    - name: Run tests
      run: raco test -p apollo 