name: Racket CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Racket
      uses: Bogdanp/setup-racket@v1.11
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.16'
    
    - name: Install non-built-in build dependencies
      run: raco pkg install --batch rackunit scribble-lib

    - name: Setup apollo package (compiles and handles deps)
      run: raco setup apollo
    
    - name: Run tests
      run: raco test -p apollo 