name: Deploy VitePress Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  # pull_request: # Keep disabled for now unless PR previews are needed

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Needed for peaceiris/actions-gh-pages
      pages: write    # Needed for peaceiris/actions-gh-pages with deploy_type: 'github_pages'
      id-token: write # Needed for peaceiris/actions-gh-pages with deploy_type: 'github_pages' if OIDC is used
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            docs/package-lock.json
            docs/package.json

      - name: Install Dependencies
        working-directory: ./docs
        run: |
          npm install
          npm cache verify

      - name: Build VitePress Site
        working-directory: ./docs
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist 