name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0, v2.1.3, etc.

jobs:
  build:
    name: Build for ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true # Add this to checkout submodules (like themes)

      # --- Hugo Setup and Build ---
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest' # Or specify a version
          # extended: true # Uncomment if using Sass/SCSS

      - name: Build Hugo site
        # Run hugo within the docs directory
        # Output will be in docs/public by default
        run: hugo --source docs/
        shell: bash
      # --- End Hugo Setup and Build ---

      - name: Set up Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: 'x64' # Assumes x64 for all OS for now
          distribution: 'full'
          variant: 'CS'
          version: '8.16' # Use the version consistent with ci.yml

      - name: Link local package
        run: raco pkg install --batch

      - name: Build release binaries (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          raco exe --output apollo-binary src/apollo/main.rkt
          cp apollo-binary apollo-rojo
          cp apollo-binary build-exe
        # Ensure this script places apollo-binary, apollo-rojo, build-exe in the root

      - name: Build release binaries (Windows)
        if: runner.os == 'Windows'
        # TODO: Replace with your actual Windows build command (e.g., PowerShell)
        # Ensure this script places apollo-binary.exe, apollo-rojo.exe, build-exe.exe in the root
        run: |
          raco exe --output apollo-binary src/apollo/main.rkt
          # raco exe adds .exe automatically on Windows
          Copy-Item apollo-binary.exe apollo-rojo.exe
          Copy-Item apollo-binary.exe build-exe.exe
        shell: pwsh # Use PowerShell for Copy-Item

      # TODO: Adjust paths and names if your build script outputs differently or with extensions
      - name: Upload Artifacts (Linux/macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-and-docs-${{ matrix.os }} # Rename artifact to reflect content
          path: |
            apollo-binary
            apollo-rojo
            build-exe
            docs/public # Add built docs site
          retention-days: 1

      - name: Upload Artifacts (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-and-docs-${{ matrix.os }} # Rename artifact to reflect content
          # Assuming .exe extensions are added by the build process
          path: |
            apollo-binary.exe
            apollo-rojo.exe
            build-exe.exe
            docs/public # Add built docs site
          retention-days: 1

  release:
    name: Create GitHub Release
    needs: build # Run after all builds are complete
    runs-on: ubuntu-latest # The OS for the release step doesn't matter much
    permissions:
      contents: write # Needed to create releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for release note generation

      - name: Create download directory
        run: mkdir -p release-assets

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets # Download all artifacts into this directory
          # Artifacts will be in subdirectories like release-assets/binaries-and-docs-ubuntu-latest/

      - name: List downloaded files # Optional: for debugging
        run: ls -R release-assets
        shell: bash

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          # Use a glob pattern to upload all files from the artifact subdirectories
          artifacts: release-assets/**/*
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true 